# Generated by Django 5.2.7 on 2025-10-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_urls',
        ),
        migrations.RemoveField(
            model_name='product',
            name='retailer',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=models.URLField(db_index=True, max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vegan_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('VEGAN', 'Vegan'), ('NON_VEGAN', 'Not Vegan'), ('UNSURE', 'Unsure')], default='PENDING', max_length=10),
        ),
    ]
