# Generated by Django 5.2.7 on 2025-11-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vegan_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('VEGAN', 'Vegan'), ('NON_VEGAN', 'Not Vegan'), ('UNSURE', 'Unsure')], default='PENDING', max_length=15),
        ),
    ]
