# Generated by Django 5.2.7 on 2025-11-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_vegan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vegan_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('VEGAN', 'Vegan'), ('NON_VEGAN', 'Not Vegan'), ('UNSURE', 'Unsure')], default='PENDING', max_length=20),
        ),
    ]
