# Generated by Django 5.2.7 on 2025-11-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_price_alter_product_vegan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
